### ISSUE TITLE
the README links to an old version of commonmark.js (on spec.commonmark.org)

### ISSUE THREAD

**Issue by killerswan** [jgm/commonmark.js#1]
There's a link in the README to http://spec.commonmark.org/js/commonmark.js, which is old enough that it refers to `DocParser` instead of `Parser`, so then the example usage later in the README is wrong.

If I knew where the source of that website was, I'd give you a pull request updating it.  :)

**Comment by jgm** [comment]
Sorry this is confusing.  The README in master reflects a number of changes since the last release (the version of `commonmark.js` at `spec.commonmark.org`), including the switch from DocParser to Parser.  To make matters more confusing, we just split this repository off from a main repository that used to include both a C library and a JS library, and we haven't yet reconstructed the tags indicating releases.

Anyway, this isn't really a bug, since the documentation for the development version will inevitably get out of sync with the code for a prior release.

Going forward, releases will be in the form of tarballs including both a README and the code.

**Comment by killerswan** [comment]
Gotcha.  Thanks!
