### ISSUE TITLE
Error: Cannot find module "../maps/xml.json"

### ISSUE THREAD

**Issue by kkak10** [jgm/commonmark.js#106]
I use Webpack builder.

Webpack build after, show library error.

error is Error: Cannot find module "../maps/xml.json"

I check dist/commonmark.js.

problem line is 

var inverseXML = getInverseObj(require("../maps/xml.json")),
    xmlReplacer = getInverseReplacer(inverseXML);

exports.XML = getInverse(inverseXML, xmlReplacer);

var inverseHTML = getInverseObj(require("../maps/entities.json")),
    htmlReplacer = getInverseReplacer(inverseHTML);

maps folder is not found in commonmarker.
so show errror error is Error: Cannot find module "../maps/xml.json"

Check Please. Thank you!

ps. I'm not speak English very well

**Comment by jgm** [comment]
dist/commonmark.js is generated using uglify-js.

So, I'd say this is either a bug in uglify-js, or a problem
with webpack builder or the way you're using webpack
builder.  (I know nothing about webpack builder.)

The commonmark source does not directly invoke
../maps/xml.json; this is brought in by uglify-js
when it imports the source code from the mdurl/decode
library.

You could try running webpack on the original
commonmark source (lib/index.js) instead of the
bundlede version.

+++ Lee Han Ur [Jul 17 16 20:27 ]:

**Comment by aaronbeall** [comment]
Just added `react-markdown` to my project and I'm seeing this same error.
