### ISSUE TITLE
<p> 4 spaces in and following a <ul>/<ol> converted to <pre><code>

### ISSUE THREAD

**Issue by envygeeks** [jgm/commonmark.js#115]
https://johnmacfarlane.net/babelmark2/?text=%23%23+Not+Working%0A%3Cdiv+class%3D%22broken%22%3E%0A++%3Cdiv%3E%0A++++%3Cul%3E%0A++++++%3Cli%3EWat%3F%3C%2Fli%3E%0A++++%3C%2Ful%3E%0A%0A++++%3Cp%3E+am+broken!%3C%2Fp%3E%0A++%3C%2Fdiv%3E%0A%3C%2Fdiv%3E

```
## Not Working
<div class="broken">
  <div>
    <ul>
      <li>Wat?</li>
    </ul>

    <p> am broken!</p>
  </div>
</div>
```

Results in

```
<h2>Not Working</h2>
<div class="broken">
  <div>
    <ul>
      <li>Wat?</li>
    </ul>
<pre><code>&lt;p&gt; am broken!&lt;/p&gt;
</code></pre>
  </div>
</div>
```

**Comment by jgm** [comment]
This conforms to the spec, as far as I can see.
If you think it doesn't, explain why.

Note that the spec is designed to make it possible for Markdown content to be placed between HTML tags.  If you remove the blank line after the `</ul>`, you'll get the result you desire.

**Comment by envygeeks** [comment]
What? It is literally invalid output.

**Comment by jgm** [comment]
+++ Jordon Bedwell [Aug 01 17 17:38 ]:
>   What? It is literally invalid output.

True, but there's no way to *guarantee* valid output when
raw HTML is allowed in the input.

The user just has to understand the rules as set down in
the spec, which determine which bits are parsed as raw
HTML and which bits are parsed as Markdown.

**Comment by envygeeks** [comment]
AFAIW the spec doesn't say that 4 spaces take precedence over HTML and I don't think they would ever explicitly stated such a thing. Can you link to where it implies this ambiguity?

That said this problem is easily avoidable with an AST or even a simple tokenizer (if there isn't already one)

**Comment by envygeeks** [comment]
Oh it looks like you control the spec so this is a no win situation no matter what. I guess we won't be using commonmark libs or promoting it's adoption as this is a serious problem.

**Comment by jgm** [comment]
Look at the spec for HTML blocks (4.6).

It says that

```
<div class="broken">
  <div>
    <ul>
      <li>Wat?</li>
    </ul>
```

is an HTML block, with start condition 6. This kind of
HTML block ends at the first blank line.

Hence, when we get to

```
    <p> am broken!</p>
```

we are no longer in an HTML block. Since this is indented
four spaces, it gets parsed as an indented code block.

Although I agree that in this particular case the spec
gives funny results, in general it is extremely useful
to be able to put CommonMark content inside HTML tags,
and the spec is designed to make this possible.

Simple solution 1: remove the blank line.
Simple solution 2: don't indent.

If you have better ideas for the spec, feel free to suggest
them on http://talk.commonmark.org.  But, before you do
that, please read the existing discussions, which include
mention of cases like this:
https://talk.commonmark.org/t/raw-html-blocks-proposals-comments-wanted/983/30


+++ Jordon Bedwell [Aug 02 17 06:43 ]:
