### ISSUE TITLE
CommonMark renderer

### ISSUE THREAD

**Issue by iamstarkov** [jgm/commonmark.js#27]
> The C library (cmark) has a CommonMark renderer. This could be ported over to commonmark.js (the code would be fairly similar), but I haven't done it yet.

**Comment by vladimirstarkov** [comment]
@jgm Can you point me to to the sources for CommonMark renderer in С library?

**Comment by jgm** [comment]
Sure - it's at `src/commonmark.c`.
https://github.com/jgm/cmark/blob/master/src/commonmark.c

It's a bit more complex than the other writers, because (a)
it hard-wraps lines (if requested) to a predefined margin,
and (b) it tries to decide in a semi-intelligent way when
special characters need to be escaped.  Let me know if you
have any questions.

+++ Vladimir Starkov [Apr 20 15 18:21 ]:

**Comment by iamstarkov** [comment]
I cannot find tests for CommonMark renderer in C library. Do they exists?

**Comment by jgm** [comment]
+++ Vladimir Starkov [Apr 29 15 14:42 ]:
>   I cannot find tests for CommonMark renderer in C library. Do they
>   exists?

No, there are no separate tests.  I used this to test:

    python3 test/spec_tests.py --prog test/roundtrip.sh

This takes each test case, renders it as commonmark,
then renders the result as HTML and compares it to the
spec test output.  I'm pretty happy with this as a testing
procedure, but I should at some point wire it into the
automatic test suite.

**Comment by iamstarkov** [comment]
Thanks, will try out to write commonmark renderer in next few weeks

**Comment by christianvoigt** [comment]
Any news on this? I could use a CommonMark renderer as well.

**Comment by iamstarkov** [comment]
there is no no news from me. Currently I don’t need this feature. Because my main framework is not ready

**Comment by iamstarkov** [comment]
nah, i switched to mdast https://github.com/wooorm/mdast/
