### ISSUE TITLE
Fuse/merge adjacent text nodes

### ISSUE THREAD

**Issue by robinst** [jgm/commonmark.js#34]
Currently, the AST returned by commonmark.js can contain multiple adjacent text nodes. E.g. the following ([dingus](http://spec.commonmark.org/dingus/?text=https%3A%2F%2Fwww.google.com%2F%3Fq%3Dfoo_bar)):

    https://www.google.com/?q=foo_bar

Results in this AST:

```
<document>
  <paragraph>
    <text>https://www.google.com/?q=foo</text>
    <text>_</text>
    <text>bar</text>
  </paragraph>
</document>
```

For uses that require post-processing the AST before rendering (e.g. autolinking plain URLs), this makes it a little bit more difficult, because adjacent text nodes may have to be merged first.

Could this be implemented in the inline parser directly, so that the resulting AST never contains adjacent text nodes?

This isn't really a bug report. It's more of a discussion starter, and to hear your thoughts about this. I'm thinking about how to implement auto-linking in my implementation of CommonMark, and post-processing might be a good option.

**Comment by jgm** [comment]
+++ Robin Stocker [May 07 15 01:55 ]:
>   Currently, the AST returned by commonmark.js can contain multiple
>   adjacent text nodes. E.g. the following ([1]dingus):
>https://www.google.com/?q=foo_bar
>
>   Results in this AST:
><document>
>  <paragraph>
>    <text>https://www.google.com/?q=foo</text>
>    <text>_</text>
>    <text>bar</text>
>  </paragraph>
></document>
>
>   For uses that require post-processing the AST before rendering (e.g.
>   autolinking plain URLs), this makes it a little bit more difficult,
>   because adjacent text nodes may have to be merged first.

The C library cmark contains a function `cmark_consolidate_text_nodes`, which merges adjacent text nodes.  This could easily be ported to commonmark.js.  (It's in `src/iterator.c` in the C lib.)

>   Could this be implemented in the inline parser directly, so that the
>   resulting AST never contains adjacent text nodes?

We could change the parser so that instead of creating a new text node next to an old one, it adds to the old one.  But this wouldn't quite do the trick, because of the way emphasis is handled.  The emphasis stack contains pointers to text nodes with the raw delimiters, which are manipulated and sometimes turned into emphasis, but you may also end up with loose text nodes at the end.

It would probably suffice to (a) change the parser in the way I described above, and (b) add a normalization routine to the end of `processEmphasis`.  This would have some performance cost, though, so it might be good to make it optional.  (I'm still up in the air about whether to leave it optional in the C library -- adding normalization makes my benchmark go from 0.33s to 0.34s, so we might just want to make it a standard part of the parsing routine.)

**Comment by iamstarkov** [comment]
Offtopic to issue itself, but I have a question. @jgm what do you think about nodejs bindings to C-libraries in context of cmark? it seems that you have to do huge work on porting every feature

**Comment by jgm** [comment]
@iamstarkov Sorry, I don't understand your question.  Can you say more?

**Comment by iamstarkov** [comment]
Sure, nodejs have ability to be natively extensioned by C libraries.

> Addons are dynamically linked shared objects. They can provide glue to C and C++ libraries.
— from the [Addons docs](https://nodejs.org/api/addons.html)

Basically, it means that you can expose methods from С library to nodejs package

**Comment by jgm** [comment]
I think node bindings would be useful to have (just like
perl bindings, python bindings, etc.).  Someone can take this
up as an external project; it wouldn't live in this repository.
I don't plan to do this myself.  I think for most purposes,
commonmark.js will be fast enough.

**Comment by robinst** [comment]
> It would probably suffice to (a) change the parser in the way I described above, and (b) add a normalization routine to the end of `processEmphasis`. This would have some performance cost, though, so it might be good to make it optional. (I'm still up in the air about whether to leave it optional in the C library -- adding normalization makes my benchmark go from 0.33s to 0.34s, so we might just want to make it a standard part of the parsing routine.)

Yes. I might implement that and see what effect it has on the benchmarks. I can't say when I'll get to it, but I'll update this issue (feel free to close it until then if you want).
