### ISSUE TITLE
Invalid node type

### ISSUE THREAD

**Issue by hidekatsu-izuno** [jgm/commonmark.js#63]
I'm ported commonmark.js to java (https://github.com/hidekatsu-izuno/commonmark4j).

Then I found the non existing node type HtmlInline in the xml.js. Is this not HtmlBlock?

```xml.js:javascript
        unescapedContents = nodetype === 'Html' || nodetype === 'HtmlInline';
```

**Comment by jgm** [comment]
Yes, thanks, this is a typo.

I'm not going to post an immediate fix, because this issue
raises a couple others.

1. The DTD  has types 'html' (for blocks) and 'html_inline'
(for inline), but this doesn't align with the code in the
C and js implementations.  It would be best to be
consistent.

2. Presumably we should wrap the raw HTML in CDATA?  (Both
here and in the C library?)

+++ Hidekatsu Izuno [Aug 01 15 22:47 ]:
