### ISSUE TITLE
sourcepos on links

### ISSUE THREAD

**Issue by timshannon** [jgm/commonmark.js#64]
Is there a reason why we don't get data-sourcepos on links?

`test [test](https://google.com)`

Current get:
`<p data-sourcepos="1:1-1:31">test <a href="https://google.com">test</a></p>`
Would be nice to get:
`<p data-sourcepos="1:1-1:31">test <a data-sourcepos="1:6-1:31" href="https://google.com">test</a></p>`

**Comment by jgm** [comment]
We have only implemented sourcepos for block-level elements.
It would be a bit trickier to make it work for inline
elements.  Because I think sourcepos tags aren't the way
to go anyway (see #29), I haven't put time into this.
Eventually we'll need a way of getting source maps for
all elements.

+++ Tim Shannon [Sep 01 15 14:06 ]:
