### ISSUE TITLE
Fix url normalizer

### ISSUE THREAD

**Issue by puzrin** [jgm/commonmark.js#9]
Discussed here https://github.com/jgm/CommonMark/issues/270

My last attempt to use `url` for honest parse caused tons of broken tests (see https://github.com/jgm/CommonMark/issues/270#issuecomment-75429014):

1. It always add missed `/` after domain name (`http://example.com?abc` -> `http://example.com/?abc`)
2. It replaces `\` with `/` in query `http://example.com?abc` https://github.com/joyent/node/commit/f7ede33f09187cd9b1874982e813380cd292ef17

Need to decide, what to do with (tests|spec|implementation). I've stopped working on this issue, until direction given. Code is available in separate branch https://github.com/markdown-it/markdown-it/commits/normalize (last commit).

Example:

```bash
node -e "console.log(require('url').parse('http://example.com?foo'))"
```
=>
```js
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'example.com',
  port: null,
  hostname: 'example.com',
  hash: null,
  search: '?foo',
  query: 'foo',
  pathname: '/',
  path: '/?foo',
  href: 'http://example.com/?foo' }
```
see `href`

**Comment by puzrin** [comment]
Example with `\` replacement:

```bash
node -e "console.log(require('url').parse('http://example.com?foo\\\\*'))"
```
=>
```js
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'example.com',
  port: null,
  hostname: 'example.com',
  hash: null,
  search: '?foo/*',
  query: 'foo/*',
  pathname: '/',
  path: '/?foo/*',
  href: 'http://example.com/?foo/*' }
```
see `href`

**Comment by jgm** [comment]
Sorry, I'm confused about what you're reporting.  Are you saying there's a bug with the 'url' library?  If so, that's not something I can fix.  In any case, I get different results than you do:

```
% node
> console.log(require('url').parse('http://example.com?foo\\\\*'))
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'example.com',
  port: null,
  hostname: 'example.com',
  hash: null,
  search: '?foo\\\\*',
  query: 'foo\\\\*',
  pathname: '/',
  path: '/?foo\\\\*',
  href: 'http://example.com/?foo\\\\*' }
undefined
```

Try running in interactive node rather than through the shell (maybe your shell is doing some escaping before passing things through to the library?)

**Comment by puzrin** [comment]
> Sorry, I'm confused about what you're reporting.

We have problem with how JS implementation normalize urls now ([example](http://spec.commonmark.org/dingus/?text=%5Blink%5D%28http%3A%2F%2Fgoogle.com%2F%3Fq%3D%253f%29)). As discussed before, more honest url parser is required for normalization process. I share info, that use of standard lib `url` fixed some of existing problems, but added new ones.

To see failures - checkout `normalize` branch of `markdown-it` and run tests.

For real example

> Are you saying there's a bug with the 'url' library?

It does additional normalizations on output (add / to host & lowercase it). I don't know is it good or bad (IMHO, more good than bad). But that make unable to pass current spec tests. We can partially update tests and do next iteration, or figure out, that standard library `url` is useless for our needs "as is".

Partial fix is to use `/` after domain name when path or params exist. That will hide ~2/3 of new failed tests.

In this case we will have to write our oun lib, because i don't know good alternatives for js.

> In any case, I get different results than you do

What is your node version? I suspect, it's very old. If it's < 0.10.latest - upgrade.

**Comment by jgm** [comment]
OK, the divergence was partly due to an old node version.  Now I get:

```
> console.log(require('url').parse('http://example.com?foo\\\\*'))
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'example.com',
  port: null,
  hostname: 'example.com',
  hash: null,
  search: '?foo//*',
  query: 'foo//*',
  pathname: '/',
  path: '/?foo//*',
  href: 'http://example.com/?foo//*' }
```

which is still different from what you reported, although not in a really significant way (`//` for `/`).

I understand that it is adding `/` and lowercasing the host.  What I don't understand is why it is making the `\\\\` turn into `//` or `/`.  Do you understand this?

**Comment by jgm** [comment]
First answer to this [SO question](http://stackoverflow.com/questions/10438008/different-behaviours-of-treating-backslash-in-the-url-by-firefox-and-chrome) is helpful:  "The unified solution to deal with backslash in a URL is to use %5C. RFC 2396 did not allow that character in URLs at all (so any behavior regarding that character was just error-recovery behavior). RFC 3986 does allow it, but is not widely implemented, not least because it's not exactly compatible with existing URL processors."

So, node's `url` library seems to treat the backslash as a forward slash, which is the error recovery behavior that (e.g.) Chrome uses, even though RFC 3986 allows a backslash in a URL.  I don't really understand why the `url` library doesn't simply escape the backslash as `%5C`.  That's what houdini, which we use in cmark, does, and it seems more correct.  Of course, you could simply replace `\\` with `%5C` in the url before passing it to `url.parse`, and solve the problem that way.

The issue with lowercasing domain names and adding the slash is a bit harder to deal with.  For reasons I've given before, I'd rather not require URL normalization of this kind in the spec.  But one thing we could do is modify the test runner (`spec_test.py`) so that *it* normalizes URLs in href and src attributes before comparing the actual output to the expected output.  We're already doing some HTML normalization anyway, to allow for whitespace differences &c, so this wouldn't be very difficult to do.  This approach would give some leeway to implementers about how to handle URL normalization.

**Comment by puzrin** [comment]
> What I don't understand is why it is making the `\\\\` turn into `//` or `/`. Do you understand this?

double/quad count of `\` is due bash + js string encoding. Finally, it just replace `\` to `/`. See this commit and references in it's description:

https://github.com/joyent/node/commit/f7ede33f09187cd9b1874982e813380cd292ef17

I currently use node 0.10.33. Can upgrade if needed. But as far as i see, you reproduced all major problems:

- added / after hostname (major count of broken tests)
- lowercase hostname
- replace \ with /

**Comment by puzrin** [comment]
> But one thing we could do is modify the test runner (spec_test.py) so that it normalizes URLs in href and src attributes before comparing the actual output to the expected output.

Overcomplicated, IMHO. Why not add / after hostnames and use lowercase for domains? If you don't require normalization in spec - don't test it there.

**Comment by puzrin** [comment]
I mean, spec can say directly:

> Different implementations can have (or not have) additional normalization steps. For example: ... Those are not covered intentionally, to leave freedom for developpers.

Then, move appropriate tests from spec to implementation (if you really need those).

**Comment by jgm** [comment]
> Overcomplicated, IMHO. Why not add / after hostnames and use lowercase for domains?

Because that requires parsing the URL into components.  We don't do that in cmark, and I don't think it should be required for an implementation.

> If you don't require normalization in spec - don't test it there.

I assume the alternative you have in mind is just to make sure all the URLs in the spec tests have lowercase domains and a forward slash after the hostname?  That seems a bit too fragile to me.  I'd rather add normalization to the test runner, which as I said wouldn't be hard.

> See this commit and references in it's description:
>
> joyent/node@f7ede33

I think that commit was a very bad idea.  As far as I can see, Chrome and Safari both convert a backslash to a forward slash in the path part of a URL, but *not* in the query part!  And in any case, I don't think it's a good idea for a URL normalization library to emulate an error fallback mechanism of a browser.

**Comment by puzrin** [comment]
> I assume the alternative you have in mind is just to make sure all the URLs in the spec tests have lowercase domains and a forward slash after the hostname? That seems a bit too fragile to me.

Well, if you think that such behaviour is mandatory and testing needed - write tests exactly for this behaviour. Only 2 tests should become broken, not 10. There is some difference, when test suite gives couple of errors or long list.

> I'd rather add normalization to the test runner, which as I said wouldn't be hard.

I don't like this solution. That hides problem instead of solve it. If wrapper required to test urls, original tests became useless (in spec).

**Comment by jgm** [comment]
+++ Vitaly Puzrin [Feb 22 15 10:57 ]:
>> I assume the alternative you have in mind is just to make sure all the URLs in the spec tests have lowercase domains and a forward slash after the hostname? That seems a bit too fragile to me.
>
>Well, if you think that such behaviour is mandatory and testing needed - write tests exactly for this behaviour. Only 2 tests should become broken, not 10. There is some difference, when test suite gives couple of errors or long list.

What do you mean by "such behavior"?  I have expressed the view that the spec should leave some latitude about normalization.  However, we do need tests with URLs, since every link and image has one!  So, either we have a situation where some conforming implementations will fail tests (bad) or we do some normalization of URLs in the test runner.  I see no
other alternative.

>> I'd rather add normalization to the test runner, which as I said wouldn't be hard.
>
>I don't like this solution. That hides problem instead of solve it. If wrapper required to test urls, original tests became useless (in spec).

Why?  If the spec doesn't require insertion of a slash after the domain name, then an implementation that produces either `http://google.com?q=a` or `http://google.com/?q=a` should count as passing.  For this, we need the test runner to do some normalization in comparing output.  (As I noted, we already do normalization to cover other allowed variations in HTML output.)  The test is hardly useless.  If an implementation produces `http://yahoo.com?q=a`, it will fail, etc.

**Comment by puzrin** [comment]
> What do you mean by "such behavior"?

I mean, if you wish to test, that "/" is NOT added by normalizer, write tests for it, and make sure that other url tests are not affected. Current tests try to check multiple things at once. That cause too much tests to be broken on improper behaviour. It's a good practice of unit testing - isolate tested areas, check only one thing at once.

> Why? If the spec doesn't require insertion of a slash after the domain name, then an implementation that produces either `http://google.com?q=a` or `http://google.com/?q=a` should count as passing. For this, we need the test runner to do some normalization in comparing output.

Test normalizer significantly reduces spec clearness. Because normalizer can be buggy itself, and there are no spec, what such normalizer allowed and not allowed to do. Imagine, that normalizer just replace all input with empty string. Then i can say, that any function, returning empty string is valid commonmark parser.

In case of HTML `\n` between tags we don't have a better solution. That's an exclusion, not the rule to propagate such approach everywhere.

If spec allows flexibility in url normalization, it should not include mandatory tests for such cases (i don't mean removing all tests at all). For example, tests, dependent on normalization details, can be tagged as optional, or (IMHO, best) moved to implementation. Because this behaviour depends on implementation only.

**Comment by jgm** [comment]
+++ Vitaly Puzrin [Feb 22 15 12:07 ]:
>> What do you mean by "such behavior"?
>
>I mean, if you wish to test, that "/" is NOT added by normalizer

But I've been making the point that I *don't* want to test for this.  I want an implementation to pass whether it adds this or not.  The problem is that if we have *any* URLs in the tests, and we have to in order to test links, then they will either have the trailing slash or not.  In either case, there would be some perfectly good implementations that would fail the test. Hence the need for normalization.

>> Why? If the spec doesn't require insertion of a slash after the domain name, then an implementation that produces either `http://google.com?q=a` or `http://google.com/?q=a` should count as passing. For this, we need the test runner to do some normalization in comparing output.
>
>Test normalizer significantly reduces spec clearness. Because normalizer can be buggy itself, and there are no spec, what such normalizer allowed and not allowed to do. Imagine, that normalizer just replace all input with empty string. Then i can say, that any function, returning empty string is valid commonmark parser.

Well, that normalizer would be buggy.  And sure, the normalizer needs to be tested, just like other parts of the test runner.  I just don't see how that's relevant.  Even without normalization, there are all kinds of ways in which the test runner could be buggy.

>In case of HTML `\n` between tags we don't have a better solution. That's an exclusion, not the rule to propagate such approach everywhere.
>
>If spec allows flexibility in url normalization, it should not include mandatory tests for such cases (i don't mean removing all tests at all). For example, tests, dependent on normalization details, can be tagged as optional, or (IMHO, best) moved to implementation. Because this behaviour depends on implementation only.

I'll say it again:  if there is flexibility in URL normalization (and I support that), then *any* test involving links and images will be problematic for some potential implementation.  We can't remove all tests for links and images with absolute URIs, and we can't make them optional.  So I still don't see any alternative to normalizing URLs in the test runner.  You haven't given one, or if you have, I haven't understood what it is.

Here are the choices, as I see it:

1. Mandate a particular way of normalizing URLs, as part of the spec.
2. Remove all spec examples involving links with absolute URLs, including autolinks.  Only test links and images using relative URLs.
3. Allow conforming implementations to fail tests.
4. Do some normalizing of URIs in the test runner, so that implementations can pass the tests despite diverging slightly in how they normalize URLs.

Unless I've misunderstood, you are against (1), and so am I.

I think (2) would be terrible.  We need tests for these central elements in the spec.

(3) is bad as well.  Passing the tests should be required for an implementation to be considered conforming.

So that leaves (4), unless you have another idea in mind that hasn't been considered.

**Comment by puzrin** [comment]
I'm against (4), because it replace lack of spec definition with lack of test runner definition. The system behaviour will stay not specified, but "in more complex way". In this case (1) or (3) will be much better, because defined directly.

And seems (2) is caused by misunderstanding. I did not suggested that. I said, that many tests use `http://google.com?q=a` (missed `/`) in source, instead of `http://google.com/?q=a`. If you replace such links to ones with `/`, 2/3 of broken tests in mu branch will pass, and we can be more focused on the rest.

Example: https://github.com/jgm/CommonMark/blob/master/spec.txt#L5658-L5662 . IMHO, there are no reason to use `**a<http://foo.bar?q=**>` instead of `**a<http://foo.bar/?q=**>`. Such things happens in ~10 places. They don't improve testing quality but breaks on normalizer change.

**Comment by jgm** [comment]
+++ Vitaly Puzrin [Feb 22 15 13:26 ]:

>And seems (2) is caused by misunderstanding. I did not suggested that. I said, that many tests use `http://google.com?q=a` (missed `/`) in source, instead of `http://google.com/?q=a`. If you replace such links to ones with `/`, 2/3 of broken tests in mu branch will pass, and we can be more focused on the rest.

That will help *you*.  But what if someone uses a different normalization procedure, that doesn't add the `/`?  (Remember, the idea is that these details wouldn't be mandated by the spec.)  That person will fail the tests, but they should be regarded as conforming.  So this isn't really a solution at all.

>Example: https://github.com/jgm/CommonMark/blob/master/spec.txt#L5658-L5662 . IMHO, there are no reason to use `**a<http://foo.bar?q=**>` instead of `**a<http://foo.bar/?q=**>`. Such things happens in ~10 places. They don't improve testing quality but breaks on normalizer change.

See above.

**Comment by puzrin** [comment]
> That will help *you*. But what if someone uses a different normalization procedure, that doesn't add the `/`? (Remember, the idea is that these details wouldn't be mandated by the spec.) That person will fail the tests, but they should be regarded as conforming. So this isn't really a solution at all.

I don't agree - never seen URLs you use in spec in real life (without `/` immediately after host, but with query or anchor). I gave you direct example, when your test are good for you and bad for me. And solution, which can be good for both. Why do you prefer imaginated person instead of real one :) ?

If you don't like `**a<http://foo.bar/?q=**>`, use `**a<http://foo.bar/test?q=**>` - it has no problem with `/` normalization.

And i can repeat again - don't mix completely different checks in one tests. If you care about normalization - do it separately. It's not good, when emphasis test fail because of normalizer.

**Comment by jgm** [comment]
+++ Vitaly Puzrin [Feb 22 15 14:50 ]:
>> That will help *you*. But what if someone uses a different normalization procedure, that doesn't add the `/`? (Remember, the idea is that these details wouldn't be mandated by the spec.) That person will fail the tests, but they should be regarded as conforming. So this isn't really a solution at all.
>
>I don't agree - never seen URLs you use in spec in real life (without `/` immediately after host, but with query or anchor). I gave you direct example, when your test are good for you and bad for me. And solution, which can be good for both. Why do you prefer imaginated person instead of real one :) ?

If I did what you recommend, the spec wouldn't be able to contain a simple autolink example like

    <http://example.com>

I would have to replace that with

    <http://example.com/>

I think plenty of non-imaginary people would write the first rather than the second, and the spec ought to be able to contain simple examples like that.  (This is probably the most common use of autolinks.)

My general point (focusing on this example) is that the spec should be able to have a test for

    <http://example.com>

that could be passed by implementations producing *either* of the following outputs:

    <p><a href="http://example.com">http://example.com</a></p>

which is what cmark produces, or

    <p><a href="http://example.com">http://example.com/</a></p>

which is your implementation would produce if it called `url.parse`.

In order to do this, we need URL normalization in the test runner. There is no other alternative that I can see.

>If you don't like `**a<http://foo.bar/?q=**>`, use `**a<http://foo.bar/test?q=**>` - it has no problem with `/` normalization.

I don't have a problem with changing this particular test, but it's not going to address the general problem.  Since a solution to the general problem will help with this as well, there's not much point to changing this case.

**Comment by puzrin** [comment]
Let's split things separately. I never suggested to replace http://example.com with http://example.com/, because it's a known exclusion. But spec has links like this: http://example.com?query and that's completely different thing. 

Quote from myself https://github.com/jgm/commonmark.js/issues/9#issuecomment-75468584:

> never seen URLs you use in spec in real life (without / immediately after host, __but with query or anchor__).

---

> I don't have a problem with changing this particular test, but it's not going to address the general problem. Since a solution to the general problem will help with this as well, there's not much point to changing this case.

I suggest iterative approach, because problem is difficult:

1. First step - reduce number of "not normalizers neutral" links in spec. I don't ask to completely replace everything. But leaving 2 failed tests is much more convenient than 10 failing tests.
2. Second step - let's discuss what we can do with the rest.

I stay, that specifying normalization in spec is more clear, than adding magic to test runner. The best it to generate RFC-compliant links. I have no goal to force node's `url` package work. It looks like writing markdown-specific `url` alternative will be better (similar to original, but with less forced normalizations).

**Comment by puzrin** [comment]
I've noticed URLs update, thanks a lot. We started working on https://github.com/markdown-it/mdurl . It already has `encode` implementation, suitable for commonmark:

- the same as encodeURI, but keep `%xx` intact.
- fix broken surrogate sequences instead of throw exception.

That's enougth to follow current specification and solve the most ugly bugs, caused by `decodeURI() use` before `encodeURI`. `markdown-it` switched to it without problems.

In the nearest days `.parse()` will be added. The same as node's `url.parse()`, but without forсed normalizations. That's not required by spec, but required to make rfc-compliant urls (proper domain encode) and user-friendly link texts (decode `%xx`, `xn--` and so on).

**Comment by jgm** [comment]
Great.  I am trying it out with commonmark.js.  Just wanted to make sure you intended all of the following:

- spaces are not escaped as `%20`
- non-ascii letters (e.g. Greek letters) are not percent encoded
- backslash is not percent encoded
- backtick is not percent encoded
- brackets are not percent encoded

I think that in at least some of these cases, we probably want encoding to happen, right?

+++ Vitaly Puzrin [Mar 02 15 20:50 ]:

**Comment by puzrin** [comment]
https://github.com/markdown-it/mdurl/blob/master/encode.js#L94

Default not encoded chars are [a-zA-Z0-9] + exclusions of `encodeURI()`. Everything else WILL be encoded, as required by rfc. But if something already was encoded with `%xx`, it's `%` will not be encoded twice.

Second and third params are optional. For example, to make `encode` work as js `encodeURIComponent()`. With single param it works as js `encodeURI()`, but avoids double encoding.

About greek and other letters - i guess, you mix different things. Those MUST be encoded in URL path/segments, according to rfc. But it would be nice to force decoding for url text in autolink - that's a subject of url text normalizer, not existing now.

**Comment by jgm** [comment]
+++ Vitaly Puzrin [Mar 02 15 21:46 ]:
>https://github.com/markdown-it/mdurl/blob/master/encode.js#L94
>
>Default not encoded chars are [a-zA-Z0-9] + exclusions of `encodeURI()`. Everything else WILL be encoded, as required by rfc. But if something already was encoded with `%xx`, it's `%` will not be encoded twice.
>
>Second and third params are optional. For example, to make `encode` work as js `encodeURIComponent()`. With single param it works as js `encodeURI()`, but avoids double encoding.
>
>About greek and other letters - i guess, you mix different things. Those MUST be encoded in URL path/segments, according to rfc. But it would be nice to force decoding for url text in autolink - that's a subject of url text normalizer, not existing now.

Odd, it didn't encode Greek letters or spaces in my tests.  Maybe I was using it wrong?  What I did was replace the `encodeURI(decodeURI(x))` sequence with your `encode(x, true)`.

My own view is that a normalizer is not needed for autolinks.  The "link text" part of an autolink should be taken literally from what the user wrote, and the link itself (href attribute) should be normalized.  If they write percent encoding in the autolink, it should display that way; if they write Greek letters, it should display that way.

**Comment by puzrin** [comment]
> My own view is that a normalizer is not needed for autolinks. The "link text" part of an autolink should be taken literally from what the user wrote, and the link itself (href attribute) should be normalized. If they write percent encoding in the autolink, it should display that way; if they write Greek letters, it should display that way.

I don't agree about link text. Personally, i never type complex links - i copy-paste those. When i copy-paste link from browser, it appears percent-encoded (+ IDNA-encoded domain). That looks ugly. I'd prefer to get the same text i see in browser address. May be, there are another popular use cases for "international" links, but i don't know those.

---

__About href hostname__. See last paragraph of [RFC 3986, chapter 3.2.2](http://tools.ietf.org/html/rfc3986#section-3.2.2):

- it seems, that percent-encoding instead of IDNA-encoding for hostname is allowed in browsers (that's not ideal, but acceptable).
- we can NOT know for all protocols, if those have host or not, without significant efforts.

So, we decided to use pure percent encoding for href, as simple and safe.

URL parse still will be required to normalize autolink text. But IDNA hostname decoding is actual only for limited set of protocols, easy to whitelist.

---

__What to percent-encode/decode__

RFC has no strict requirements for "viewers" (browsers), only for producers (when you click link). But when you copypaste link, everything except alphnums & eclusions, is encoded. This behaviour looks optimal for me:

- __href__ - take user input and percent-_encode_ everything except alphanums & reserved chars
- __text__ - take user input and percent-_decode_ everything except alphanums & reserved chars + IDNA-decode hostname for _limited_ list of protocols (all with `//` + `mailto:`)

That guarantee always working links, and nice looking text for most cases.

Important thing is no NEVER use decode + encode simultaneously (as reference js implementation does now).

---

That's what i'd like to do in `markdown-it` by default. If spec will require different behaviour, it's possible to replace normalizer for `commonmark` mode to pass tests.

Link text transforms are not critical, because users will customize those anyway. For example, they can wish to drop `http://` and `www.` from text. My personal preference is to keep spec tests requirements minimal (without touching IDNA encode/decode).

**Comment by puzrin** [comment]
FYI: released [mdurl](https://github.com/markdown-it/mdurl) 1.0.0. Now it has all functions, required to build normalizers with minimal efforts:

- encode
- decode
- parse/format

I hope it should help.

**Comment by jgm** [comment]
Excellent, I've just used the functions from mdurl.

**Comment by puzrin** [comment]
One question about how you fixed it here. Are you sure you really need to directly copy sources? You can set package in dependency, and use `require('mdurl/encode')` and so on. Browserify will handle it without problems. As bonus - automatic more easy updates for bugfixes.

The same for [entities](https://github.com/markdown-it/markdown-it/blob/master/package.json#L22) - IMHO it's better to delegate components maintenance outside when it's possible.

**Comment by jgm** [comment]
@vitaly I'm not sure.  I see the advantages of using the dependencies.
On the other hand, I like the fact that the reference library is
self-contained: everything you need is there.  This also helps
when people want to port the library (as someone recently did
to Java); they can see what these components do without hunting
around for dependent libraries.  Another consideration is that
I only use part of what these libraries provide -- for example,
in mdurl I don't use the parsing part, which is fairly heavy,
and my entities code only does decoding, which is all I need.
Is browserify smart enough to include just the parts you use?

**Comment by puzrin** [comment]
We speically did mdurl to be useable by components. If you require direct path, instead of root, browserify will include only that file and it's dependencies:

```js
require('mdurl').encode // will include index.js (all)
require('mdurl/encode') // will include encode.js only
```

Browserify works very simple - it resolve path, include file and do recursive pass.

The same for the entities: https://github.com/markdown-it/markdown-it/blob/master/lib/common/entities.js#L6. You can include only one file you need.

**Comment by vitaly** [comment]
@jgm I've nothing to do with this ;)
